version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - example-network

  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    restart: unless-stopped
    container_name: fastapi-app
    ports:
      - 8000:8000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tasks
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - example-network

  grpc-app:
    build:
      context: .
      dockerfile: Dockerfile.grpc
    restart: unless-stopped
    container_name: grpc-app
    ports:
      - 50051:50051
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/tasks
    env_file:
      - .env
    volumes:
      - ./.env:/app/.env:ro
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - example-network

networks:
  example-network:
    driver: bridge

volumes:
  postgres_data:
