[project]
name = "python-grpc-open-telemetry-example"
version = "0.1.0"
description = "FastAPI and GRPC share same logic"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [

]

[tool.uv.workspace]
members = ["apps/fastapi_app", "apps/grpc_app", "core"]
