# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: task.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'task.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntask.proto\x12\x04task\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"L\n\x11\x43reateTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x18\n\x0b\x64\x65scription\x18\x02 \x01(\tH\x00\x88\x01\x01\x42\x0e\n\x0c_description\"/\n\x10ListTasksRequest\x12\x0c\n\x04skip\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"6\n\x11ListTasksResponse\x12!\n\x05tasks\x18\x01 \x03(\x0b\x32\x12.task.TaskResponse\"!\n\x0eGetTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\"\x92\x01\n\x11UpdateTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\x12\n\x05title\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x18\n\x0b\x64\x65scription\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\x16\n\tcompleted\x18\x04 \x01(\x08H\x02\x88\x01\x01\x42\x08\n\x06_titleB\x0e\n\x0c_descriptionB\x0c\n\n_completed\"$\n\x11\x44\x65leteTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\"%\n\x12\x44\x65leteTaskResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"\xda\x01\n\x0cTaskResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x18\n\x0b\x64\x65scription\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x11\n\tcompleted\x18\x04 \x01(\x08\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x33\n\nupdated_at\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x01\x88\x01\x01\x42\x0e\n\x0c_descriptionB\r\n\x0b_updated_at2\xb7\x02\n\x0bTaskService\x12\x39\n\nCreateTask\x12\x17.task.CreateTaskRequest\x1a\x12.task.TaskResponse\x12<\n\tListTasks\x12\x16.task.ListTasksRequest\x1a\x17.task.ListTasksResponse\x12\x33\n\x07GetTask\x12\x14.task.GetTaskRequest\x1a\x12.task.TaskResponse\x12\x39\n\nUpdateTask\x12\x17.task.UpdateTaskRequest\x1a\x12.task.TaskResponse\x12?\n\nDeleteTask\x12\x17.task.DeleteTaskRequest\x1a\x18.task.DeleteTaskResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATETASKREQUEST']._serialized_start=82
  _globals['_CREATETASKREQUEST']._serialized_end=158
  _globals['_LISTTASKSREQUEST']._serialized_start=160
  _globals['_LISTTASKSREQUEST']._serialized_end=207
  _globals['_LISTTASKSRESPONSE']._serialized_start=209
  _globals['_LISTTASKSRESPONSE']._serialized_end=263
  _globals['_GETTASKREQUEST']._serialized_start=265
  _globals['_GETTASKREQUEST']._serialized_end=298
  _globals['_UPDATETASKREQUEST']._serialized_start=301
  _globals['_UPDATETASKREQUEST']._serialized_end=447
  _globals['_DELETETASKREQUEST']._serialized_start=449
  _globals['_DELETETASKREQUEST']._serialized_end=485
  _globals['_DELETETASKRESPONSE']._serialized_start=487
  _globals['_DELETETASKRESPONSE']._serialized_end=524
  _globals['_TASKRESPONSE']._serialized_start=527
  _globals['_TASKRESPONSE']._serialized_end=745
  _globals['_TASKSERVICE']._serialized_start=748
  _globals['_TASKSERVICE']._serialized_end=1059
# @@protoc_insertion_point(module_scope)
