global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    metrics_path: /prometheus/metrics
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'fastapi-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['fastapi-app:8000']
  - job_name: 'grpc-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['grpc-app:50052']
